### ISSUE TITLE
cant autorole

### ISSUE THREAD

**Issue by zarigata** [Dav-Git/Dav-Cogs#105]
Traceback (most recent call last):
  File "/root/redenv/lib/python3.9/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "/root/.local/share/Red-DiscordBot/data/storm/cogs/CogManager/cogs/autoroler/autoroler.py", line 35, in on_member_join
    await member.add_roles(*[member.guild.get_role(role_id) for role_id in data["roles"]])
  File "/root/redenv/lib/python3.9/site-packages/discord/member.py", line 777, in add_roles
    await req(guild_id, user_id, role.id, reason=reason)
  File "/root/redenv/lib/python3.9/site-packages/discord/http.py", line 248, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

**Comment by Dav-Git** [comment]
Your bot seems to be missing the required permissions to assign roles.
