### ISSUE TITLE
[supporter] Error's + suggestions

### ISSUE THREAD

**Issue by Brandjuh** [Dav-Git/Dav-Cogs#40]
When someone creates a ticket but it timedout the following error will arrive

```
Traceback (most recent call last):
  File "/root/redenv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 83, in wrapped
    ret = await coro(*args, **kwargs)
  File "/root/.local/share/Red-DiscordBot/data/cuffbotv3/cogs/CogManager/cogs/supporter/supporter.py", line 155, in create
    dept_msg = await self.bot.wait_for(
  File "/usr/lib/python3.8/asyncio/tasks.py", line 490, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/redenv/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 892, in invoke
    await ctx.command.invoke(ctx)
  File "/root/redenv/lib/python3.8/site-packages/redbot/core/commands/commands.py", line 799, in invoke
    await super().invoke(ctx)
  File "/root/redenv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1234, in invoke
    await ctx.invoked_subcommand.invoke(ctx)
  File "/root/redenv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 797, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/root/redenv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 92, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: TimeoutError: 
```

Also I have a the following suggestions::
1) Option to remove the `[p]ticket create` so a dedicated channel for creating tickets is not clogged.
2) Option to purge all closed tickets, so they are removed.
3) Option to show list of departments `[p]supporter department list`

**Comment by Dav-Git** [comment]
Option 1 is already taken care of by ``[p]set deletedelay`` in core. I'll definitely work on the rest

**Comment by Brandjuh** [comment]
Another suggestion based of ticket tool bot that I would like. (If you do not want implent it its fine)

![image](https://user-images.githubusercontent.com/26203955/83863224-5762ad00-a723-11ea-895b-0e7c2cd87034.png)
Option to use emoji's in stead of text. 
- Make a message with explain text and that user can hit the emoji to open the ticket. 


![image](https://user-images.githubusercontent.com/26203955/83863278-6c3f4080-a723-11ea-8a2c-d0def77b85c7.png)
Option to ask for department in in the ticket.
- User will be asked for the department in a "pre-screening" ticket. Different departments are listed there with 1/2/3/4 etc. User can click the emoji of the department to open the real ticket.  
- Maybe its better to add this to the explain message.

![image](https://user-images.githubusercontent.com/26203955/83863481-ad375500-a723-11ea-9ad2-359f2b7e71f4.png)
And maybe also the option for transscription. 
![image](https://user-images.githubusercontent.com/26203955/83863571-c93af680-a723-11ea-946c-ef6794ae3c79.png)

**Comment by Dav-Git** [comment]
Emojis won't be a thing. I don't see the benefit. And it's a hassle to implement. If someone wants to PR it, I'm up for it. Otherwise no.

Similar thing goes for saving a transcript. The reason I don't delete channels is to save a "log" of the ticket. As far as I know taking the messages outside of discord would be a breach of TOS
