### ISSUE TITLE
[Ticketer]Error on load

### ISSUE THREAD

**Issue by 1illeke** [Dav-Git/Dav-Cogs#51]
[2020-07-17 15:07:40] [ERROR] red: Package loading failed
Traceback (most recent call last):
  File "/home/lilleke/redenv/lib/python3.8/site-packages/redbot/core/core_commands.py", line 119, in _load
    await bot.load_extension(spec)
  File "/home/lilleke/redenv/lib/python3.8/site-packages/redbot/core/bot.py", line 929, in load_extension
    lib = spec.loader.load_module()
  File "<frozen importlib._bootstrap_external>", line 462, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 962, in load_module
  File "<frozen importlib._bootstrap_external>", line 787, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/lilleke/.local/share/Red-DiscordBot/data/bnl/cogs/CogManager/cogs/ticketer/__init__.py", line 1, i
n <module>
    from .Ticketer import Ticketer
ModuleNotFoundError: No module named 'ticketer.Ticketer'

Getting this error when trying to load the cog :)

**Comment by Dav-Git** [comment]
I can't reproduce this, are you sure you're using an up to date version? Did you modify the cog at all or are you using a fork? Next time please put the error in a codeblock by wrapping it with 3 backticks. `

**Comment by Dav-Git** [comment]
I'll be closing this issue due to no activity.
