### ISSUE TITLE
listexclusives with over 1024 characters give error.

### ISSUE THREAD

**Issue by Skyridr** [Dav-Git/Dav-Cogs#64]
Apparently I added way too much exclusives, as listing it shows that it's over 1024 characters:

```py
Traceback (most recent call last):
  File "/home/satan/.virtualenvs/satan/lib/python3.8/site-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/satan/satan/cogs/CogManager/cogs/exclusiveroles/exclusiveroles.py", line 109, in listexclusives
    await ctx.send(embed=embed)
  File "/home/satan/.virtualenvs/satan/lib/python3.8/site-packages/redbot/core/commands/context.py", line 93, in send
    return await super().send(content=content, **kwargs)
  File "/home/satan/.virtualenvs/satan/lib/python3.8/site-packages/discord/abc.py", line 890, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed,
  File "/home/satan/.virtualenvs/satan/lib/python3.8/site-packages/discord/http.py", line 245, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In embed.fields.0.value: Must be 1024 or fewer in length.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/satan/.virtualenvs/satan/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 903, in invoke
    await ctx.command.invoke(ctx)
  File "/home/satan/.virtualenvs/satan/lib/python3.8/site-packages/discord/ext/commands/core.py", line 855, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/home/satan/.virtualenvs/satan/lib/python3.8/site-packages/discord/ext/commands/core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In embed.fields.0.value: Must be 1024 or fewer in length.
```

Maybe split them up in pages instead?

**Comment by Dav-Git** [comment]
Oh boi yes how did you get past that. Lmao. I'll see how I can add pagination to this.

**Comment by Dav-Git** [comment]
This should be fixed now. Give it another try.
